'use client';
import { useState } from 'react';
import Image from 'next/image';
import { motion, AnimatePresence } from 'framer-motion';
import { BadgeCheck, Camera, Copy, Heart, MessageCircle, Play, Shuffle, Upload, BarChart3, Share2 } from 'lucide-react';
import { artist, tracks } from '@/lib/mock-data';
import { compactNumber } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { MusicCard } from './music-card';
import { EditProfileModal } from './edit-profile-modal';
const tabs = ['Overview','Tracks','Albums','Singles','Playlists','Videos','Reposts','About','Events','Merchandise','Support'];
export function ArtistProfile() { const [tab,setTab]=useState('Overview'); const [edit,setEdit]=useState(false); const isOwner=true; return <main className="min-h-screen pb-28"><header className="sticky top-0 z-40 border-b border-white/10 bg-background/80 backdrop-blur-xl"><nav className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><div className="text-xl font-black tracking-tight">Aurora<span className="text-primary">Sound</span></div><div className="hidden flex-1 px-8 md:block"><input aria-label="Search music" placeholder="Search tracks, artists, albums" className="w-full rounded-full border border-border bg-white/60 px-5 py-2 text-sm dark:bg-white/5"/></div><Button className="bg-primary text-primary-foreground">Upgrade</Button></nav></header>
<div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 lg:grid-cols-[1fr_340px]"><section className="min-w-0"><Hero onEdit={()=>setEdit(true)} isOwner={isOwner}/><TabBar tab={tab} setTab={setTab} isOwner={isOwner} onEdit={()=>setEdit(true)}/><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} className="mt-7 space-y-8"><Overview tab={tab}/></motion.div></AnimatePresence></section><RightSidebar/></div><BottomPlayer/><EditProfileModal open={edit} onOpenChange={setEdit}/></main> }
function Hero({isOwner,onEdit}:{isOwner:boolean;onEdit:()=>void}){return <section className="relative overflow-hidden rounded-[2rem] shadow-glow"><Image src={artist.bannerUrl} alt="Artist banner" width={1600} height={520} priority className="h-[430px] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/35 to-black/10"/><div className="absolute right-5 top-5 flex gap-2">{isOwner&&<Button className="bg-black/55 text-white backdrop-blur"><Camera size={16}/> Replace banner</Button>}</div><div className="absolute inset-x-0 bottom-0 flex flex-col gap-5 p-5 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end"><div className="relative w-fit"><Image src={artist.avatarUrl} alt={`${artist.name} profile picture`} width={168} height={168} className="size-36 rounded-full border-4 border-white object-cover shadow-2xl sm:size-44"/>{isOwner&&<button aria-label="Edit profile picture" className="focus-ring absolute bottom-3 right-3 rounded-full bg-primary p-3 text-white shadow-lg"><Camera size={18}/></button>}</div><div className="max-w-3xl text-white"><div className="flex items-center gap-3"><h1 className="text-4xl font-black tracking-tight sm:text-6xl">{artist.name}</h1>{artist.verified&&<BadgeCheck className="text-sky-300"/>}</div><p className="mt-2 text-white/80">@{artist.username} • {artist.location} • {artist.genres.join(' / ')}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-white/85">{artist.bio}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-sm sm:grid-cols-6">{[['Monthly',artist.monthlyListeners],['Plays',artist.totalPlays],['Followers',artist.followers],['Following',artist.following],['Tracks',artist.tracks],['Albums',artist.albums]].map(([k,v])=><div key={k as string} className="rounded-2xl bg-white/10 p-3 backdrop-blur"><dt className="text-white/60">{k}</dt><dd className="font-black">{compactNumber(v as number)}</dd></div>)}</dl></div></div></div></section>}
function TabBar({tab,setTab,isOwner,onEdit}:{tab:string;setTab:(t:string)=>void;isOwner:boolean;onEdit:()=>void}){return <div className="sticky top-[61px] z-30 mt-4 rounded-3xl border border-white/10 bg-background/85 p-3 backdrop-blur-xl"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-2 overflow-x-auto scrollbar-hide" role="tablist" aria-label="Artist profile sections">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`focus-ring whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold transition ${tab===t?'bg-primary text-white':'bg-white/60 hover:bg-white dark:bg-white/5 dark:hover:bg-white/10'}`}>{t}</button>)}</div><div className="flex gap-2 overflow-x-auto scrollbar-hide"><Button className="bg-primary text-white"><Heart size={16}/> Follow</Button><Button className="bg-slate-900 text-white dark:bg-white dark:text-slate-950"><Play size={16}/> Play All</Button><Button className="bg-white/70 dark:bg-white/10"><Shuffle size={16}/> Shuffle</Button><Button className="bg-white/70 dark:bg-white/10"><Share2 size={16}/> Share</Button><Button className="bg-white/70 dark:bg-white/10"><Copy size={16}/> Copy</Button><Button className="bg-white/70 dark:bg-white/10"><MessageCircle size={16}/> Message</Button>{isOwner&&<><Button onClick={onEdit} className="bg-amber-400 text-slate-950">Edit Profile</Button><Button className="bg-white/70 dark:bg-white/10"><Upload size={16}/> Upload</Button><Button className="bg-white/70 dark:bg-white/10"><BarChart3 size={16}/> Analytics</Button></>}</div></div></div>}
function Overview({tab}:{tab:string}){return <><section><h2 className="mb-4 text-2xl font-black">{tab==='Overview'?'Featured releases':tab}</h2><div className="grid gap-4">{tracks.slice(0, tab==='Overview'?5:9).map((track,index)=><MusicCard key={track.id} track={track} index={index}/>)}</div></section><section className="grid gap-4 md:grid-cols-3"><Info title="About" text={artist.bio}/><Info title="Collaborations" text="Open for select features, soundtrack briefs, and intimate live sessions."/><Info title="Support" text="Fans can unlock demos, stems, and behind-the-scenes studio notes."/></section></>}
function Info({title,text}:{title:string;text:string}){return <article className="rounded-3xl border border-white/10 bg-white/70 p-5 dark:bg-white/[.06]"><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{text}</p></article>}
function RightSidebar(){return <aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><div className="rounded-[2rem] border border-white/10 bg-white/70 p-5 dark:bg-white/[.06]"><h2 className="text-xl font-black">Artist statistics</h2><div className="mt-4 grid grid-cols-2 gap-3">{[['Followers',artist.followers],['Total likes',531000],['Profile views',1900000],['Monthly',artist.monthlyListeners]].map(([k,v])=><div key={k as string} className="rounded-2xl bg-slate-100 p-3 dark:bg-white/5"><p className="text-xs text-slate-500">{k}</p><p className="text-lg font-black">{compactNumber(v as number)}</p></div>)}</div><div className="mt-5 space-y-2 text-sm"><p><b>Website:</b> {artist.website}</p><p><b>Booking:</b> {artist.email}</p><p><b>Joined:</b> {artist.joinedAt}</p></div></div><div className="rounded-[2rem] border border-white/10 bg-white/70 p-5 dark:bg-white/[.06]"><h3 className="font-black">About details</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">Languages: Hindi, English. Hometown: Vadodara. Label: independent.</p><div className="mt-4 flex flex-wrap gap-2">{[...artist.achievements,...artist.equipment,...artist.influences].map(x=><span key={x} className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{x}</span>)}</div></div><div className="rounded-[2rem] border border-white/10 bg-white/70 p-5 dark:bg-white/[.06]"><h3 className="font-black">Recently liked</h3>{tracks.slice(5,8).map(t=><div key={t.id} className="mt-3 flex items-center gap-3"><Image src={t.cover} alt="" width={44} height={44} className="rounded-xl"/><div><p className="text-sm font-bold">{t.title}</p><p className="text-xs text-slate-500">Recommended</p></div></div>)}</div></aside>}
function BottomPlayer(){return <div className="fixed inset-x-0 bottom-0 z-50 border-t border-white/10 bg-background/90 p-3 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-4"><Button className="bg-primary text-white"><Play size={18}/></Button><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">Drippin’ Slow — Prince Vadgama</p><div className="mt-2 h-1 rounded-full bg-slate-200 dark:bg-white/10"><div className="h-full w-1/3 rounded-full bg-primary"/></div></div><span className="text-xs text-slate-500">1:02 / 2:28</span></div></div>}
